# CYOA Scenario Platform
#
# No `set shell` override, deliberately: this justfile runs in this
# repo's Dev Container, GitHub Actions (bash-only ubuntu-latest runner),
# and homelab's migrate.py (Alpine, no zsh/bash installed for a uv.lock
# repo) - see deploys/apps.yaml's `migrate_command: "just migrate"`.
# `just`'s own default, plain POSIX `sh -cu`, is the one thing guaranteed
# present everywhere.

set dotenv-load

project := `basename "$(pwd)"`
db_name := "cyoa"

# Read from the Compose secret mount - only valid inside the Dev
# Container. Generated once per workspace by .devcontainer/generate-secrets.sh
# and reused across restarts/rebuilds; never regenerated by `just`.
#
# database_url respects an already-set DATABASE_URL env var first:
# homelab's migrate.py sets a real DATABASE_URL (from the production k8s
# Secret) before running `just migrate`, which has no /run/secrets/* at
# all (that only exists in this workspace's own Compose containers).
# Always computing a local default unconditionally would silently
# override that and break production migrations - see
# link108/cutty-bangerz's justfile for the incident that taught us this.
#
# postgresql+asyncpg:// (not plain postgresql://) since the backend uses
# SQLAlchemy's async engine with the asyncpg driver.
postgres_user := `cat /run/secrets/postgres_user 2>/dev/null || true`
postgres_password := `cat /run/secrets/postgres_password 2>/dev/null || true`
database_url := env_var_or_default("DATABASE_URL", "postgresql+asyncpg://" + postgres_user + ":" + postgres_password + "@postgres:5432/" + db_name)

default:
    @just --list

# === Setup ===

# Install backend + frontend dependencies
install:
    cd backend && uv sync
    cd frontend && npm install

# Create .env from the documented template when it does not exist.
env:
    @if [ ! -f .env ]; then cp .env.example .env; echo "Created .env"; else echo ".env already exists"; fi

# First-time setup inside a freshly created Dev Container: dependencies,
# env file, and database schema/seed. Postgres already exists by this
# point (devcontainer.json's initializeCommand + Compose health checks
# handle that before you get a shell). Safe to run repeatedly.
setup: install env
    @just migrate
    @just seed
    @echo "Ready. Run: just api (and, separately, just web)"

# === Development ===

# Run the API with reload (expects migrations applied - see `just setup`/`just migrate`)
api:
    cd backend && DATABASE_URL="{{ database_url }}" uv run uvicorn app.main:app --reload --port 8000

# Run the frontend dev server (proxies /api to :8000)
web:
    cd frontend && npm run dev

# === Database ===

# Apply migrations (what homelab's migrate.py runs in production)
migrate:
    cd backend && DATABASE_URL="{{ database_url }}" uv run alembic upgrade head

# Create a new migration from model changes
migration name:
    cd backend && DATABASE_URL="{{ database_url }}" uv run alembic revision --autogenerate -m "{{ name }}"

# Seed the scenario library from committed fixtures (backend/app/seed_data)
seed *args:
    cd backend && DATABASE_URL="{{ database_url }}" uv run python -m app.seed {{ args }}

# Generate library fixtures from the catalog via the AI builder (needs DEEPSEEK_API_KEY + db)
seed-generate *args:
    cd backend && DATABASE_URL="{{ database_url }}" uv run python -m app.seed_generate {{ args }}

# Run the living-scenarios news pass once (drafts land in /admin for review)
living-run:
    cd backend && DATABASE_URL="{{ database_url }}" uv run python -m app.living_run

# Open a psql shell against DATABASE_URL (psql doesn't understand the
# +asyncpg driver suffix SQLAlchemy needs, so strip it).
psql:
    psql "{{ replace(database_url, "+asyncpg", "") }}"

# === API contract ===

# Regenerate the committed OpenAPI contract (openapi.json at repo root)
openapi:
    cd backend && uv run python -m app.openapi_export

# === Quality ===

# Backend tests (sqlite, stubbed LLM - no DATABASE_URL/key needed)
test:
    cd backend && uv run pytest

lint:
    cd backend && uv run ruff check .
    cd frontend && npx tsc -b

fmt:
    cd backend && uv run ruff format . && uv run ruff check --fix .

# Same as CI.
alias ci := check

check: lint test

# === Docker (production image) ===

# Build the production image (API + built SPA in one container)
docker-build:
    docker build -t link108/game-theory-sim:latest .

# Run the production image against a separate, host-reachable Postgres
# (not this workspace's own Dev Container Postgres - a different,
# unrelated flow, same as `just db-up` used to provide before this repo
# moved to the isolated Dev Container Postgres above). Start one
# yourself first, e.g. `docker run -d -p 5433:5432 -e POSTGRES_PASSWORD=postgres postgres:16-alpine`.
docker-run:
    docker run --rm -p 8000:8000 \
        -e DATABASE_URL="postgresql+asyncpg://postgres:postgres@host.docker.internal:5433/cyoa" \
        -e DEEPSEEK_API_KEY="$DEEPSEEK_API_KEY" \
        link108/game-theory-sim:latest

# --- Workspace lifecycle (run from the HOST, not inside the Dev Container -
# these need Docker access to manage the Compose project itself) ---------

# Show this workspace's container status.
status:
    docker compose -f compose.dev.yml -p {{ project }} ps

# Follow this workspace's container logs.
logs:
    docker compose -f compose.dev.yml -p {{ project }} logs -f --tail=100

# Stop this workspace's containers. Preserves the database volume and
# generated credentials - resume with `devcontainer up` or `just api`.
stop:
    docker compose -f compose.dev.yml -p {{ project }} down

# DESTROYS this workspace's containers, database volume, and generated
# credentials. Only ever touches THIS checkout's own resources (scoped by
# Compose project name, i.e. this directory's name) - never another
# worktree, repo, or workspace.
[confirm("This deletes ALL local data and credentials for this workspace. Continue?")]
destroy:
    @echo "Destroying workspace: {{ project }}"
    docker compose -f compose.dev.yml -p {{ project }} down -v
    rm -rf .devcontainer/secrets
    @echo "Workspace destroyed. Run 'devcontainer up' to start fresh with new credentials."
