"""add scenario category and is_library

Revision ID: 779257e57d84
Revises: a41f9c2d5e83
Create Date: 2026-07-14 13:59:45.037955

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '779257e57d84'
down_revision: str | None = 'a41f9c2d5e83'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'scenarios',
        sa.Column('category', sa.String(length=100), nullable=False, server_default=''),
    )
    op.add_column(
        'scenarios',
        sa.Column('is_library', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_index(op.f('ix_scenarios_is_library'), 'scenarios', ['is_library'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenarios_is_library'), table_name='scenarios')
    op.drop_column('scenarios', 'is_library')
    op.drop_column('scenarios', 'category')
    # ### end Alembic commands ###
