"""initial schema

Revision ID: 78c60dd8d971
Revises: 
Create Date: 2026-07-08 15:23:45.623151

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '78c60dd8d971'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anon_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('request', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_cache_key'), 'llm_calls', ['cache_key'], unique=True)
    op.create_table('scenarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_session_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('premise', sa.Text(), nullable=False),
    sa.Column('setting', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=200), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('gm_notes', sa.Text(), nullable=False),
    sa.Column('roles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('npcs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_session_id'], ['anon_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_owner_session_id'), 'scenarios', ['owner_session_id'], unique=False)
    op.create_table('playthroughs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('owner_session_id', sa.Uuid(), nullable=False),
    sa.Column('role_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_session_id'], ['anon_sessions.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playthroughs_owner_session_id'), 'playthroughs', ['owner_session_id'], unique=False)
    op.create_index(op.f('ix_playthroughs_scenario_id'), 'playthroughs', ['scenario_id'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('playthrough_id', sa.Uuid(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('player_view', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('gm_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('chosen_option_id', sa.String(length=50), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('regen_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playthrough_id'], ['playthroughs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playthrough_id', 'index', name='uq_turn_playthrough_index')
    )
    op.create_index(op.f('ix_turns_playthrough_id'), 'turns', ['playthrough_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turns_playthrough_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_playthroughs_scenario_id'), table_name='playthroughs')
    op.drop_index(op.f('ix_playthroughs_owner_session_id'), table_name='playthroughs')
    op.drop_table('playthroughs')
    op.drop_index(op.f('ix_scenarios_owner_session_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_llm_calls_cache_key'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_table('anon_sessions')
    # ### end Alembic commands ###
