const DEEPSEEK_PRIVACY =
  "https://cdn.deepseek.com/policies/en-US/deepseek-privacy-policy.html?locale=en_US";
const DEEPSEEK_PLATFORM_TERMS =
  "https://cdn.deepseek.com/policies/en-US/deepseek-open-platform-terms-of-service.html";
const DEEPSEEK_MODEL_INFO =
  "https://cdn.deepseek.com/policies/en-US/model-algorithm-disclosure.html";

export default function FAQ() {
  return (
    <div className="faq-page">
      <p className="eyebrow">FAQ & safety</p>
      <h1>Use simulations as practice, not authority</h1>
      <p className="page-intro">
        Scenario Sim is an experimental roleplay and decision-practice tool. Its responses are
        generated by an AI model and can be incomplete, misleading, or wrong.
      </p>

      <section className="faq-section">
        <h2>Who generates the scenarios and responses?</h2>
        <p>
          Scenario Sim uses the DeepSeek API to generate intake questions, scenario turns,
          suggested actions, and analyses. DeepSeek is a third-party AI provider. Scenario Sim is
          not sponsored, endorsed, or operated by DeepSeek.
        </p>
      </section>

      <section className="faq-section">
        <h2>What information is sent to DeepSeek?</h2>
        <p>
          The app sends the scenario, the context you provide, your role, your choices, and the
          current simulated state to DeepSeek when it needs a response. Do not enter names,
          addresses, dates of birth, account numbers, medical record numbers, confidential
          business information, or other identifying or sensitive information.
        </p>
        <p>
          DeepSeek's published privacy policy says its services are not designed for sensitive
          personal data, including health information. It also says downstream applications are
          responsible for their own disclosures. Review DeepSeek's current{" "}
          <a href={DEEPSEEK_PRIVACY} target="_blank" rel="noreferrer">
            privacy policy
          </a>{" "}
          and{" "}
          <a href={DEEPSEEK_PLATFORM_TERMS} target="_blank" rel="noreferrer">
            open-platform terms
          </a>
          .
        </p>
      </section>

      <section className="faq-section">
        <h2>What does Scenario Sim store?</h2>
        <p>
          This deployment stores scenarios, playthroughs, choices, context-intake answers and
          summaries, generated responses, and cached model requests in its database. There is not
          currently a self-service data deletion tool. Avoid submitting information you would not
          want retained by this deployment or processed by its AI provider.
        </p>
      </section>

      <section className="faq-section">
        <h2>Is this medical, legal, financial, or other professional advice?</h2>
        <p>
          No. The simulations are educational practice and do not provide diagnosis, treatment,
          triage, legal advice, financial advice, or any professional-client relationship. Do not
          start, stop, or change treatment, medication, contracts, investments, or other
          consequential actions based on an AI response. Consult a qualified professional who can
          evaluate the real situation.
        </p>
      </section>

      <section className="faq-section">
        <h2>What should I do in an emergency?</h2>
        <p>
          Do not use Scenario Sim. Contact local emergency services or an appropriate crisis
          service immediately. The app cannot monitor you, contact responders, or guarantee that
          it will recognize an emergency.
        </p>
      </section>

      <section className="faq-section">
        <h2>Can AI output be wrong?</h2>
        <p>
          Yes. AI can invent facts, misunderstand context, omit important risks, or express false
          confidence. DeepSeek's own model disclosure says generated content is for reference and
          should not be treated as professional advice. Read its{" "}
          <a href={DEEPSEEK_MODEL_INFO} target="_blank" rel="noreferrer">
            model and training disclosure
          </a>
          .
        </p>
      </section>

      <section className="faq-section disclaimer-section">
        <h2>Important disclaimer</h2>
        <p>
          Scenario Sim is provided "as is" for voluntary educational and entertainment use,
          without guarantees of accuracy, completeness, availability, fitness for a particular
          purpose, or outcomes. You remain responsible for verifying information and for your own
          decisions and actions. To the fullest extent permitted by applicable law, the operator
          disclaims liability for loss, injury, or damage arising from reliance on generated
          content or use of the service.
        </p>
      </section>
    </div>
  );
}
